name: android-gradle-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      appName: whisper.cpp.android.java
      tagName: v1.5.4
      targetZip: whisper.cpp.android.java-${{ github.ref_name }}.zip
    steps:
      # - uses: actions/checkout@v4
      
      - name: Clone
        uses: actions/checkout@v4
        with:
          path: whisper.cpp
          
      - run: |
          cd whisper.cpp/examples/whisper.android.java/app/src/main/assets
          mkdir models
          cd models
          curl https://huggingface.co/safecantonese/ggml-models/resolve/main/whisper-small-yue-hk.bin?download=true -L -O -J 
          
      - run: |
          cd whisper.cpp/examples/whisper.android.java/app/src/main/assets
          mkdir samples
          
      - run: |
          cp elderly-converted-16khz.wav whisper.cpp/examples/whisper.android.java/app/src/main/assets/samples/

      - run: |
          cd whisper.cpp/examples/whisper.android.java/app/src/main/assets
          ls -R
          
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Build
        run: |
          cd whisper.cpp/examples/whisper.android.java && \
          chmod +x ./gradlew && \
          ./gradlew --no-daemon assembleRelease
          
      - run: cd whisper.cpp/examples/whisper.android.java/app/build/outputs/apk && ls -R
      
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "whisper.cpp/examples/whisper.android.java/app/build/outputs/apk/release/app-release.apk"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
